name: file_browser
description: A modern file browser application supporting WebDAV, FTP, and local files.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # State management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Navigation
  go_router: ^13.0.1
  
  # Remote protocols
  webdav_client: ^1.2.1
  ftpconnect: ^2.0.5
  
  # Local storage & permissions
  path_provider: ^2.1.2
  permission_handler: ^11.1.0
  file_picker: ^6.1.1
  
  # UI components
  flutter_adaptive_scaffold: ^0.1.7+1
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  
  # Utilities
  dio: ^5.4.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  path: ^1.8.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  rxdart: ^0.27.7
  share_plus: ^7.2.1
  
  # File previewing
  open_file: ^3.3.2
  flutter_pdfview: ^1.3.2
  video_player: ^2.8.1
  just_audio: ^0.9.36
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
