name: file_browser
description: A modern file browser application supporting WebDAV and local files.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core
  path: ^1.8.3
  intl: ^0.19.0
  
  # State management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Navigation
  go_router: ^13.0.1
  
  # Remote protocols
  webdav_client: ^1.2.2
  dio: ^5.4.0
  
  # Storage & permissions
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  
  # File handling
  file_picker: ^9.0.0
  open_file: ^3.3.2
  share_plus: ^7.2.1
  
  # Media preview
  photo_view: ^0.14.0
  video_player: ^2.8.1
  just_audio: ^0.9.36
  flutter_pdfview: ^1.3.2
  
  # Utilities
  rxdart: ^0.27.7
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
